# Generating a tag utils
# By Hongyu Xiong, 04/02/2017

import math
import os
import random
import sys
import time
import re

import editdistance as ed
import numpy as np
import scratch

class Config(object):
    word_dim = 100
    vocabulary_path = '../data/vocab10000.from'
    glove_path = '../../glove.6B/glove.6B.100d.txt'
    max_vocabulary_size = 500000

    embedding_matrix, vocab, word_vector = scratch.generateEmbedMatrix(vocabulary_path, max_vocabulary_size, glove_path)
    # all keys for word_vector are in lowercase

    field2word = {
			'sum': {'value_type': 'string', 
                       'value_range': ['total', 'combined'], 
                       'query_word': ['sum','summation']},
			'diff': {'value_type': 'string', 
                       'value_range': [], 
                       'query_word': ['difference']},
			'less': {'value_type': 'string', 
                       'value_range': [], 
                       'query_word': ['less']},
			'greater': {'value_type': 'string', 
                       'value_range': ['larger'], 
                       'query_word': ['more']},
      'mean': {'value_type': 'string', 
                       'value_range': [], 
                       'query_word': ['mean', 'average']},
			'argmax': {'value_type': 'string', 
                       'value_range': ['maximum','max'],# ,'last', 'previous','before'
                       'query_word': ['most','greatest']}, #,'greatest'
			'argmin': {'value_type': 'string', 
                       'value_range': ['minimum'], #,'first', 'next','after'
                       'query_word': ['least']},
			'Masters': {'value_type':'int',
						'query_word': ['masters']},
			'Country':{'value_type': 'string', 
                     'value_range': ['Brazil', 'Canada', 'Qatar', 'Italy', 'Peru', 'Kuwait', 'New_Zealand', 'Luxembourg', 'France',
                        'HK', 'Slovakia', 'Ireland', 'Nigeria', 'Norway', 'Argentina', 'South_Korea', 'Israel',
                        'Australia', 'Iran', 'Indonesia', 'West_Germany', 'Iceland', 'Slovenia', 'China', 'Chile',
                        'Belgium', 'Germany', 'Iraq', 'Philippines', 'Poland', 'Spain', 'Ukraine', 'Hungary',
                        'Netherlands', 'Denmark', 'Turkey', 'Finland', 'Sweden', 'Vietnam', 'Thailand', 'Switzerland',
                        'Russia', 'Pakistan', 'Romania', 'Portugal', 'Mexico', 'Egypt', 'Soviet_Union', 'Singapore',
                        'India', 'Liechtenstein', 'US', 'Czech', 'Austria', 'Yugoslavia', 'Saudi_Arabia', 'UK',
                        'Greece', 'Japan', 'Taiwan'], 
                     'query_word': ['country','countries']},
      'U.S._Open': {'value_type':'int',
						'query_word': ['us','open']},
			'The_Open': {'value_type':'int',
						'query_word': ['the', 'open']},
			'PGA': {'value_type':'int',
						'query_word': ['pga']},
			'Team':{'value_type': 'string', 
                     'value_range': ['Brazil', 'Canada', 'Qatar', 'Italy', 'Peru', 'Kuwait', 'New_Zealand', 'Luxembourg', 'France',
                        'HK', 'Slovakia', 'Ireland', 'Nigeria', 'Norway', 'Argentina', 'South_Korea', 'Israel',
                        'Australia', 'Iran', 'Indonesia', 'West_Germany', 'Iceland', 'Slovenia', 'China', 'Chile',
                        'Belgium', 'Germany', 'Iraq', 'Philippines', 'Poland', 'Spain', 'Ukraine', 'Hungary',
                        'Netherlands', 'Denmark', 'Turkey', 'Finland', 'Sweden', 'Vietnam', 'Thailand', 'Switzerland',
                        'Russia', 'Pakistan', 'Romania', 'Portugal', 'Mexico', 'Egypt', 'Soviet_Union', 'Singapore',
                        'India', 'Liechtenstein', 'US', 'Czech', 'Austria', 'Yugoslavia', 'Saudi_Arabia', 'UK',
                        'Greece', 'Japan', 'Taiwan'], 
                     'query_word': ['team','nation']},
      'County':{'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['county']},
      'Years': {'value_type':'int',
						'query_word': ['years']},
			'Wins': {'value_type':'int',
						'query_word': ['wins']},
			'Areas': {'value_type':'int',
						'query_word': ['area','areas']},
			'Prices': {'value_type':'int',
						'query_word': ['prices', 'price']},
      'Swara': {'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['swara']},
      'Short_name': {'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['short','name']},
      'Notation': {'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['notation']},
      'Mnemonic': {'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['mnemonic']},
			'Player': {'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['player']},
			'Matches': {'value_type':'int',
						'query_word': ['matches','match']},
			'Innings': {'value_type':'int',
						'query_word': ['innings']},
			'Runs': {'value_type':'int',
						'query_word': ['runs','run']},
			'Average': {'value_type':'int',
						'query_word': ['average']},
			'100s': {'value_type':'int',
						'query_word': ['100s']},
			'50s': {'value_type':'int',
						'query_word': ['50s']},
			'Games_Played': {'value_type':'int',
						'query_word': ['games']},
			'Field_Goals': {'value_type':'int',
						'query_word': ['field', 'goals']},
			'Free_Throws': {'value_type':'int',
						'query_word': ['free', 'throws']},
			'Points': {'value_type':'int',
						'query_word': ['points']},
			'Menteri_Besar': {'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['menteri','besar']},
			'Party':{'value_type': 'string', 
                     'value_range': ['Conservatives', 'Green', 'Independent', 'Labour'], 
                     'query_word': ['party']},
			'Took_office':{'value_type': 'string', 
                     'value_range': ['Conservatives', 'Green', 'Independent', 'Labour'], 
                     'query_word': ['take', 'took']},
      'Left_office':{'value_type': 'string', 
                     'value_range': [], 
                     'query_word': ['leave', 'left']},
			'Nation':{'value_type': 'string', 
                     'value_range': ['Brazil', 'Canada', 'Qatar', 'Italy', 'Peru', 'Kuwait', 'New_Zealand', 'Luxembourg', 'France',
                        'HK', 'Slovakia', 'Ireland', 'Nigeria', 'Norway', 'Argentina', 'South_Korea', 'Israel',
                        'Australia', 'Iran', 'Indonesia', 'West_Germany', 'Iceland', 'Slovenia', 'China', 'Chile',
                        'Belgium', 'Germany', 'Iraq', 'Philippines', 'Poland', 'Spain', 'Ukraine', 'Hungary',
                        'Netherlands', 'Denmark', 'Turkey', 'Finland', 'Sweden', 'Vietnam', 'Thailand', 'Switzerland',
                        'Russia', 'Pakistan', 'Romania', 'Portugal', 'Mexico', 'Egypt', 'Soviet_Union', 'Singapore',
                        'India', 'Liechtenstein', 'US', 'Czech', 'Austria', 'Yugoslavia', 'Saudi_Arabia', 'UK',
                        'Greece', 'Japan', 'Taiwan'], 
                     'query_word': ['country','nation']},
			'Rank': {'value_type':'int',
						'query_word': ['rank', 'ranked']},
			'Gold': {'value_type':'int',
						'query_word': ['gold']},
			'Silver': {'value_type':'int',
						'query_word': ['silver']},
			'Bronze': {'value_type':'int',
						'query_word': ['bronze']},
			'Total': {'value_type':'int',
						'query_word': ['total']},
			'Name': {'value_type':'string',
						'value_range':[],
						'query_word': ['name', 'who']},
			'Position': {'value_type':'string',
						'value_range':['goalkeeper','defender','midfielder'],
						'query_word': ['position']},
			'Year_inducted': {'value_type':'int',
						'query_word': ['year']},
			'Apps': {'value_type':'int',
						'query_word': ['appearance','appearances']},
			'Goals': {'value_type':'int',
						'query_word': ['goal','goals']},
			'Total_Apps': {'value_type':'int',
						'query_word': ['appearance','appearances']},
			'Total_Goals': {'value_type':'int',
						'query_word': ['goal','goals']},
			'League_Apps': {'value_type':'int',
						'query_word': ['appearance','appearances']},
			'League_Goals': {'value_type':'int',
						'query_word': ['goal','goals']},
			'FA_Cup_Apps': {'value_type':'int',
						'query_word': ['appearance','appearances']},
			'FA_Cup_Goals': {'value_type':'int',
						'query_word': ['goal','goals']},
			'State': {'value_type':'string',
						'value_range':['California','Texas','Florida','Louisiana'],
						'query_word': ['state']},
			'No._of_elected': {'value_type':'int',
						'query_word': ['elected']},
			'No._of_candidates': {'value_type':'int',
						'query_word': ['candidate', 'candidates']},
			'Total_no._of_seats_in_Assembly': {'value_type':'int',
						'query_word': ['seat', 'seats']},
			'Year_of_Election': {'value_type':'int',
						'query_word': ['year']},
			'Year': {'value_type':'int',
						'query_word': ['year']},
			'1st_Venue': {'value_type': 'string', 
                       'value_range': ['Amsterdam', 'Antwerp', 'Athens', 'Atlanta', 'Bangkok', 'Barcelona', 'Beijing', 'Berlin',
                          'Budapest', 'Buenos_Aires', 'Cairo', 'Cape_Town', 'Chamonix', 'Chicago', 'Cortina_Ampezzo',
                          'Dallas', 'Delhi', 'Dubai', 'Dublin', 'Florence', 'Grenoble', 'Helsinki', 'Hong_Kong',
                          'Innsbruck', 'Istanbul', 'Jerusalem', 'Lake_Placid', 'Las_Vegas', 'London', 'Los_Angeles',
                          'Madrid', 'Melbourne', 'Mexico_City', 'Milan', 'Montreal', 'Moscow', 'Mumbai', 'Munich',
                          'New_York', 'Oslo', 'Paris', 'Philadelphia', 'Prague', 'Rio_de_Janeiro', 'Rome', 'San_Diego',
                          'Sapporo', 'Sarajevo', 'Seattle', 'Seoul', 'Macau', 'Squaw_Valley', 'St._Moritz',
                          'Stockholm', 'Sydney', 'Tokyo', 'Toronto', 'Venice', 'Vienna', 'Warsaw'], 
                       'query_word': ['city', 'cities','venue']}, 
            '2nd_Venue': {'value_type': 'string', 
                       'value_range': ['Amsterdam', 'Antwerp', 'Athens', 'Atlanta', 'Bangkok', 'Barcelona', 'Beijing', 'Berlin',
                          'Budapest', 'Buenos_Aires', 'Cairo', 'Cape_Town', 'Chamonix', 'Chicago', 'Cortina_Ampezzo',
                          'Dallas', 'Delhi', 'Dubai', 'Dublin', 'Florence', 'Grenoble', 'Helsinki', 'Hong_Kong',
                          'Innsbruck', 'Istanbul', 'Jerusalem', 'Lake_Placid', 'Las_Vegas', 'London', 'Los_Angeles',
                          'Madrid', 'Melbourne', 'Mexico_City', 'Milan', 'Montreal', 'Moscow', 'Mumbai', 'Munich',
                          'New_York', 'Oslo', 'Paris', 'Philadelphia', 'Prague', 'Rio_de_Janeiro', 'Rome', 'San_Diego',
                          'Sapporo', 'Sarajevo', 'Seattle', 'Seoul', 'Macau', 'Squaw_Valley', 'St._Moritz',
                          'Stockholm', 'Sydney', 'Tokyo', 'Toronto', 'Venice', 'Vienna', 'Warsaw'], 
                       'query_word': ['city', 'venue']}, 
            '3rd_Venue': {'value_type': 'string', 
                       'value_range': ['Amsterdam', 'Antwerp', 'Athens', 'Atlanta', 'Bangkok', 'Barcelona', 'Beijing', 'Berlin',
                          'Budapest', 'Buenos_Aires', 'Cairo', 'Cape_Town', 'Chamonix', 'Chicago', 'Cortina_Ampezzo',
                          'Dallas', 'Delhi', 'Dubai', 'Dublin', 'Florence', 'Grenoble', 'Helsinki', 'Hong_Kong',
                          'Innsbruck', 'Istanbul', 'Jerusalem', 'Lake_Placid', 'Las_Vegas', 'London', 'Los_Angeles',
                          'Madrid', 'Melbourne', 'Mexico_City', 'Milan', 'Montreal', 'Moscow', 'Mumbai', 'Munich',
                          'New_York', 'Oslo', 'Paris', 'Philadelphia', 'Prague', 'Rio_de_Janeiro', 'Rome', 'San_Diego',
                          'Sapporo', 'Sarajevo', 'Seattle', 'Seoul', 'Macau', 'Squaw_Valley', 'St._Moritz',
                          'Stockholm', 'Sydney', 'Tokyo', 'Toronto', 'Venice', 'Vienna', 'Warsaw'], 
                       'query_word': ['city', 'venue']}, 
            '4th_Venue': {'value_type': 'string', 
                       'value_range': ['Amsterdam', 'Antwerp', 'Athens', 'Atlanta', 'Bangkok', 'Barcelona', 'Beijing', 'Berlin',
                          'Budapest', 'Buenos_Aires', 'Cairo', 'Cape_Town', 'Chamonix', 'Chicago', 'Cortina_Ampezzo',
                          'Dallas', 'Delhi', 'Dubai', 'Dublin', 'Florence', 'Grenoble', 'Helsinki', 'Hong_Kong',
                          'Innsbruck', 'Istanbul', 'Jerusalem', 'Lake_Placid', 'Las_Vegas', 'London', 'Los_Angeles',
                          'Madrid', 'Melbourne', 'Mexico_City', 'Milan', 'Montreal', 'Moscow', 'Mumbai', 'Munich',
                          'New_York', 'Oslo', 'Paris', 'Philadelphia', 'Prague', 'Rio_de_Janeiro', 'Rome', 'San_Diego',
                          'Sapporo', 'Sarajevo', 'Seattle', 'Seoul', 'Macau', 'Squaw_Valley', 'St._Moritz',
                          'Stockholm', 'Sydney', 'Tokyo', 'Toronto', 'Venice', 'Vienna', 'Warsaw'], 
                       'query_word': ['city', 'venue']}, 
            '5th_Venue': {'value_type': 'string', 
                       'value_range': ['Amsterdam', 'Antwerp', 'Athens', 'Atlanta', 'Bangkok', 'Barcelona', 'Beijing', 'Berlin',
                          'Budapest', 'Buenos_Aires', 'Cairo', 'Cape_Town', 'Chamonix', 'Chicago', 'Cortina_Ampezzo',
                          'Dallas', 'Delhi', 'Dubai', 'Dublin', 'Florence', 'Grenoble', 'Helsinki', 'Hong_Kong',
                          'Innsbruck', 'Istanbul', 'Jerusalem', 'Lake_Placid', 'Las_Vegas', 'London', 'Los_Angeles',
                          'Madrid', 'Melbourne', 'Mexico_City', 'Milan', 'Montreal', 'Moscow', 'Mumbai', 'Munich',
                          'New_York', 'Oslo', 'Paris', 'Philadelphia', 'Prague', 'Rio_de_Janeiro', 'Rome', 'San_Diego',
                          'Sapporo', 'Sarajevo', 'Seattle', 'Seoul', 'Macau', 'Squaw_Valley', 'St._Moritz',
                          'Stockholm', 'Sydney', 'Tokyo', 'Toronto', 'Venice', 'Vienna', 'Warsaw'], 
                       'query_word': ['city', 'venue']}, 
            '6th_Venue': {'value_type': 'string', 
                       'value_range': ['Amsterdam', 'Antwerp', 'Athens', 'Atlanta', 'Bangkok', 'Barcelona', 'Beijing', 'Berlin',
                          'Budapest', 'Buenos_Aires', 'Cairo', 'Cape_Town', 'Chamonix', 'Chicago', 'Cortina_Ampezzo',
                          'Dallas', 'Delhi', 'Dubai', 'Dublin', 'Florence', 'Grenoble', 'Helsinki', 'Hong_Kong',
                          'Innsbruck', 'Istanbul', 'Jerusalem', 'Lake_Placid', 'Las_Vegas', 'London', 'Los_Angeles',
                          'Madrid', 'Melbourne', 'Mexico_City', 'Milan', 'Montreal', 'Moscow', 'Mumbai', 'Munich',
                          'New_York', 'Oslo', 'Paris', 'Philadelphia', 'Prague', 'Rio_de_Janeiro', 'Rome', 'San_Diego',
                          'Sapporo', 'Sarajevo', 'Seattle', 'Seoul', 'Macau', 'Squaw_Valley', 'St._Moritz',
                          'Stockholm', 'Sydney', 'Tokyo', 'Toronto', 'Venice', 'Vienna', 'Warsaw'], 
                       'query_word': ['city', 'venue']}, 
			'host_city':{'value_type': 'string', 
                       'value_range': ['Amsterdam', 'Antwerp', 'Athens', 'Atlanta', 'Bangkok', 'Barcelona', 'Beijing', 'Berlin',
                          'Budapest', 'Buenos_Aires', 'Cairo', 'Cape_Town', 'Chamonix', 'Chicago', 'Cortina_Ampezzo',
                          'Dallas', 'Delhi', 'Dubai', 'Dublin', 'Florence', 'Grenoble', 'Helsinki', 'Hong_Kong',
                          'Innsbruck', 'Istanbul', 'Jerusalem', 'Lake_Placid', 'Las_Vegas', 'London', 'Los_Angeles',
                          'Madrid', 'Melbourne', 'Mexico_City', 'Milan', 'Montreal', 'Moscow', 'Mumbai', 'Munich',
                          'New_York', 'Oslo', 'Paris', 'Philadelphia', 'Prague', 'Rio_de_Janeiro', 'Rome', 'San_Diego',
                          'Sapporo', 'Sarajevo', 'Seattle', 'Seoul', 'Macau', 'Squaw_Valley', 'St._Moritz',
                          'Stockholm', 'Sydney', 'Tokyo', 'Toronto', 'Venice', 'Vienna', 'Warsaw'], 
                       'query_word': ['city', 'cities']}, 
        	'#_participants':{'value_type': 'int', 
                            'query_word': ['participate', 'participates', 'participated', 'participant', 'participants']},
        	'#_audience':{'value_type': 'int', 
                        'query_word': ['audience']},
        	'#_medals':{'value_type': 'int', 
                      'query_word': ['medal', 'medals']},
        	'country_size':{'value_type': 'int', 
                          'query_word': ['large', 'larger', 'largest']}, 
        	'country_gdp':{'value_type': 'int', 
                         'query_word': ['gdp', 'wealth', 'wealthy', 'wealthier']}, 
        	'country_population':{'value_type': 'int', 
                                'query_word': ['population', 'people']}, 
        	'#_duration':{'value_type': 'int', 
                        'query_word': ['long', 'longer', 'longest', 'duration', 'day', 'days']},
        	'year':{'value_type': 'int', 
                  'query_word': ['year', 'years']}, 
        	'country':{'value_type': 'string', 
                     'value_range': ['Brazil', 'Canada', 'Qatar', 'Italy', 'Peru', 'Kuwait', 'New_Zealand', 'Luxembourg', 'France',
                        'HK', 'Slovakia', 'Ireland', 'Nigeria', 'Norway', 'Argentina', 'South_Korea', 'Israel',
                        'Australia', 'Iran', 'Indonesia', 'West_Germany', 'Iceland', 'Slovenia', 'China', 'Chile',
                        'Belgium', 'Germany', 'Iraq', 'Philippines', 'Poland', 'Spain', 'Ukraine', 'Hungary',
                        'Netherlands', 'Denmark', 'Turkey', 'Finland', 'Sweden', 'Vietnam', 'Thailand', 'Switzerland',
                        'Russia', 'Pakistan', 'Romania', 'Portugal', 'Mexico', 'Egypt', 'Soviet_Union', 'Singapore',
                        'India', 'Liechtenstein', 'US', 'Czech', 'Austria', 'Yugoslavia', 'Saudi_Arabia', 'UK',
                        'Greece', 'Japan', 'Taiwan'], 
                     'query_word': ['country','countries']}}

